### PR TITLE
Fix for Issue #13: Updated Interfaces for Home, Bot, and Free Mode

### PR DESCRIPTION
**Pull request by yashvisharma1204**
Hi, I have made changes to the Home, Bot, and Free Mode interfaces. Please review these changes and let me know if they are good to proceed. Once approved, I will continue applying similar updates to the remaining pages.

Thank you for your guidance!

### CODE REVIEW

**Comment by Navneet1206** [comment]
Hi @yashvisharma1204 ,

Thank you for making the changes to the Home, Bot, and Free Mode interfaces! I will review these changes shortly and provide feedback. Once approved, feel free to proceed with applying similar updates to the remaining pages.

Heartfelt thanks for your hard work and dedication to improving the project! 😊

Best regards,
Navneet

**Review by Navneet1206 — APPROVED** [review]
Hi @yashvisharma1204 ,

Thank you so much for your commit! The UI updates you’ve made are fantastic, and they really enhance the overall look and feel of the project. Your design work is truly impressive!

However, I noticed that the "connect" function was missing in the initial commit. No worries though, I’ve added it, and it’s now successfully connected!

Thanks again for your amazing contributions, and keep up the great work! 😊

Best regards,
Navneet

**Comment by yashvisharma1204** [comment]
> Hi @yashvisharma1204 ,
> 
> Thank you so much for your commit! The UI updates you’ve made are fantastic, and they really enhance the overall look and feel of the project. Your design work is truly impressive!
> 
> However, I noticed that the "connect" function was missing in the initial commit. No worries though, I’ve added it, and it’s now successfully connected!
> 
> Thanks again for your amazing contributions, and keep up the great work! 😊
> 
> Best regards, Navneet

Thank you so much for your appreciation, being a first time contributor , it's pretty hard to understand the contribution steps! I will be working on few changes related to leftover pages once it will be all done I will pull request for the same! 😊
Quick question, I noticed that Online mode connect button isn't working and start game button isnt working, like its not connecting just wanted to make sure it's not working for me or it hasn't been coded yet!

**Comment by Navneet1206** [comment]
> > Hi @yashvisharma1204 ,
> > 
> > Thank you so much for your commit! The UI updates you’ve made are fantastic, and they really enhance the overall look and feel of the project. Your design work is truly impressive!
> > 
> > However, I noticed that the "connect" function was missing in the initial commit. No worries though, I’ve added it, and it’s now successfully connected!
> > 
> > Thanks again for your amazing contributions, and keep up the great work! 😊
> > 
> > Best regards, Navneet
> 
> Thank you so much for your appreciation, being a first time contributor , it's pretty hard to understand the contribution steps! I will be working on few changes related to leftover pages once it will be all done I will pull request for the same! 😊
> Quick question, I noticed that Online mode connect button isn't working and start game button isnt working, like its not connecting just wanted to make sure it's not working for me or it hasn't been coded yet!

Most welcome @yashvisharma1204 .
Yes, I coded for online mode but you know the difficult level of maintaining the Blockchain with respect to Backend for the Online moves sharing using socket.io. That's why it not working. But in future may be it work.

Best regards,
Navneet

**Pull request merged**
